//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ops
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTrackingDelivery
    {
        public long OrderTrackingDeliveryId { get; set; }
        public long OrderId { get; set; }
        public long CarrierTrackingNumber { get; set; }
        public string CarrierStaffName { get; set; }
        public string CarrierStaffId { get; set; }
        public System.DateTime TimeBegin { get; set; }
        public System.DateTime EstimatedTimeFinish { get; set; }
        public Nullable<System.DateTime> ActualTimeFinish { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
