//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ops
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public long PaymentTypeId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string PaymentTypeName { get; set; }
        public string PaymentTypeCode { get; set; }
        public string TermsAndConditions { get; set; }
        public Nullable<System.TimeSpan> LimitTimeOnTransaction { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
