//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ops
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPS_DBEntities : DbContext
    {
        public OPS_DBEntities()
            : base("name=OPS_DBEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 20;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Log> Log { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderDetail> OrderDetail { get; set; }
        public DbSet<OrderPaid> OrderPaid { get; set; }
        public DbSet<OrderTrackingDelivery> OrderTrackingDelivery { get; set; }
        public DbSet<OrderType> OrderType { get; set; }
        public DbSet<PaymentType> PaymentType { get; set; }
        public DbSet<TransactionStatus> TransactionStatus { get; set; }
    }
}
