//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.OrderTrackingDelivery = new HashSet<OrderTrackingDelivery>();
        }
    
        public long OrderId { get; set; }
        public string TransactionStatusCode { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string PaymentTypeCode { get; set; }
        public string OrderTypeCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<long> CardTypeId { get; set; }
        public Nullable<long> BankId { get; set; }
        public Nullable<long> CardNumber { get; set; }
        public string CardHolderName { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ShipToAddress { get; set; }
        public long ShipToDistrict { get; set; }
        public long ShipToCity { get; set; }
        public Nullable<decimal> PriceWeight { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public Nullable<System.DateTime> DueTransactionTime { get; set; }
        public string OrderCode { get; set; }
        public string OrderDescription { get; set; }
        public Nullable<int> TotalProduct { get; set; }
        public Nullable<decimal> SubTotalFee { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> TaxFee { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public string TransactionCode { get; set; }
        public decimal TransactionFee { get; set; }
        public string TransactionStatusCode_BK { get; set; }
        public Nullable<bool> IsOrderConfirmed { get; set; }
        public Nullable<bool> IsPaymentConfirmed { get; set; }
        public Nullable<bool> IsWarning { get; set; }
        public Nullable<bool> IsDeliveryConfirmed { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string ReasonFail { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeliveryEnd { get; set; }
        public Nullable<System.DateTime> DateDeliveryStart { get; set; }
        public Nullable<System.DateTime> DateReceive { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> DeliveryBy { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<OrderTrackingDelivery> OrderTrackingDelivery { get; set; }
    }
}
