//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.acs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACS_DBEntities : DbContext
    {
        public ACS_DBEntities()
            : base("name=ACS_DBEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 20;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ads> Ads { get; set; }
        public DbSet<AdsCategory> AdsCategory { get; set; }
        public DbSet<AdsChannel> AdsChannel { get; set; }
        public DbSet<AdsType> AdsType { get; set; }
        public DbSet<DbTable> DbTable { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<LogDetail> LogDetail { get; set; }
        public DbSet<LogType> LogType { get; set; }
        public DbSet<AdsContent> AdsContent { get; set; }
    }
}
