//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.lps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventory
    {
        public long ProductInventoryId { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> BrandId { get; set; }
        public string Code { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> SizeId { get; set; }
    }
}
