//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.lps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        public long ProductItemId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string ProductStatusCode { get; set; }
        public string ProductBarCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<double> StandardPrice { get; set; }
        public string ProductTermService { get; set; }
        public Nullable<System.DateTime> DateManufactured { get; set; }
        public Nullable<int> LimitWarrantyDays { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
