//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.WebUI.eCommerce.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTTelecom.WebUI.eCommerce.Common.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        internal static string _continue {
            get {
                return ResourceManager.GetString("_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        internal static string _new {
            get {
                return ResourceManager.GetString("_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết nhận xét.
        /// </summary>
        internal static string add_comment {
            get {
                return ResourceManager.GetString("add_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm.
        /// </summary>
        internal static string added {
            get {
                return ResourceManager.GetString("added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ.
        /// </summary>
        internal static string addtocart {
            get {
                return ResourceManager.GetString("addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi.
        /// </summary>
        internal static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ trống.
        /// </summary>
        internal static string alert_address_null {
            get {
                return ResourceManager.GetString("alert_address_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn ngân hàng.
        /// </summary>
        internal static string alert_bank_null {
            get {
                return ResourceManager.GetString("alert_bank_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh trống.
        /// </summary>
        internal static string alert_birthdate_null {
            get {
                return ResourceManager.GetString("alert_birthdate_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận không đúng.
        /// </summary>
        internal static string alert_captch_not_match {
            get {
                return ResourceManager.GetString("alert_captch_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công.
        /// </summary>
        internal static string alert_change_complete {
            get {
                return ResourceManager.GetString("alert_change_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi không thành công.
        /// </summary>
        internal static string alert_change_fail {
            get {
                return ResourceManager.GetString("alert_change_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đồng ý các điều khoản trên.
        /// </summary>
        internal static string alert_check_agree_my_company {
            get {
                return ResourceManager.GetString("alert_check_agree_my_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đồng ý điều khoản công ty.
        /// </summary>
        internal static string alert_check_agree_sign_up {
            get {
                return ResourceManager.GetString("alert_check_agree_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn vào đây.
        /// </summary>
        internal static string alert_clickthis {
            get {
                return ResourceManager.GetString("alert_clickthis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập nội dung.
        /// </summary>
        internal static string alert_content_value_null {
            get {
                return ResourceManager.GetString("alert_content_value_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua sắm.
        /// </summary>
        internal static string alert_continue_buy {
            get {
                return ResourceManager.GetString("alert_continue_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo Đơn hàng. Vui lòng kiểm tra thông tin nhập..
        /// </summary>
        internal static string alert_create_fail_order {
            get {
                return ResourceManager.GetString("alert_create_fail_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại.
        /// </summary>
        internal static string alert_email_exist {
            get {
                return ResourceManager.GetString("alert_email_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại.
        /// </summary>
        internal static string alert_email_not_exist {
            get {
                return ResourceManager.GetString("alert_email_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email rỗng.
        /// </summary>
        internal static string alert_email_null {
            get {
                return ResourceManager.GetString("alert_email_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc, trang này không tồn tại.
        /// </summary>
        internal static string alert_error_not_exist {
            get {
                return ResourceManager.GetString("alert_error_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết bạn đã nhấp vào có thể bị hỏng, hoặc trang này có thể đã được gỡ bỏ.
        /// </summary>
        internal static string alert_error_not_exist_2 {
            get {
                return ResourceManager.GetString("alert_error_not_exist_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh quá lớn, kích thước tối đa cho phép:.
        /// </summary>
        internal static string alert_file_large {
            get {
                return ResourceManager.GetString("alert_file_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin không tồn tại.
        /// </summary>
        internal static string alert_file_not_exist {
            get {
                return ResourceManager.GetString("alert_file_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng tải hình ảnh kiểu: .
        /// </summary>
        internal static string alert_file_type_upload {
            get {
                return ResourceManager.GetString("alert_file_type_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ trống.
        /// </summary>
        internal static string alert_firstname_null {
            get {
                return ResourceManager.GetString("alert_firstname_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galagala vận chuyển MIỄN PHÍ các đơn hàng từ .
        /// </summary>
        internal static string alert_freeship_1 {
            get {
                return ResourceManager.GetString("alert_freeship_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ở .
        /// </summary>
        internal static string alert_freeship_2 {
            get {
                return ResourceManager.GetString("alert_freeship_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ .
        /// </summary>
        internal static string alert_freeship_3 {
            get {
                return ResourceManager.GetString("alert_freeship_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  các tỉnh thành khác.
        /// </summary>
        internal static string alert_freeship_4 {
            get {
                return ResourceManager.GetString("alert_freeship_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trong tài khoản.
        /// </summary>
        internal static string alert_in_account {
            get {
                return ResourceManager.GetString("alert_in_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ trống.
        /// </summary>
        internal static string alert_input_address_null {
            get {
                return ResourceManager.GetString("alert_input_address_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thẻ trống.
        /// </summary>
        internal static string alert_input_card_name {
            get {
                return ResourceManager.GetString("alert_input_card_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản 16 kí tự.
        /// </summary>
        internal static string alert_input_cardnumber {
            get {
                return ResourceManager.GetString("alert_input_cardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc mật khẩu không đúng.
        /// </summary>
        internal static string alert_input_login_fail {
            get {
                return ResourceManager.GetString("alert_input_login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng từ 1 đến 100.
        /// </summary>
        internal static string alert_input_number_quantity {
            get {
                return ResourceManager.GetString("alert_input_number_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đt trống.
        /// </summary>
        internal static string alert_input_phone_null {
            get {
                return ResourceManager.GetString("alert_input_phone_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận trống.
        /// </summary>
        internal static string alert_input_receivername_null {
            get {
                return ResourceManager.GetString("alert_input_receivername_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật không đúng.
        /// </summary>
        internal static string alert_key_not_match {
            get {
                return ResourceManager.GetString("alert_key_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trống.
        /// </summary>
        internal static string alert_lastname_null {
            get {
                return ResourceManager.GetString("alert_lastname_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải từ 6 đến 20 kí tự.
        /// </summary>
        internal static string alert_password_between_6_to_20 {
            get {
                return ResourceManager.GetString("alert_password_between_6_to_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã đóng. Vui lòng xem sản phẩm khác..
        /// </summary>
        internal static string alert_product_close {
            get {
                return ResourceManager.GetString("alert_product_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm đã hết. Bạn có thể gọi điện thoại cho chúng tôi để đặt hàng khi có sản phẩm về..
        /// </summary>
        internal static string alert_product_expired {
            get {
                return ResourceManager.GetString("alert_product_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chưa kích hoạt.
        /// </summary>
        internal static string alert_product_not_active {
            get {
                return ResourceManager.GetString("alert_product_not_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các sản phẩm đã thanh toán nhưng chưa giao hàng.
        /// </summary>
        internal static string alert_product_not_delivery {
            get {
                return ResourceManager.GetString("alert_product_not_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sản phẩm.
        /// </summary>
        internal static string alert_product_not_find {
            get {
                return ResourceManager.GetString("alert_product_not_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập lại không đúng.
        /// </summary>
        internal static string alert_repassword_not_match {
            get {
                return ResourceManager.GetString("alert_repassword_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tiêu đề.
        /// </summary>
        internal static string alert_reviewname_value_null {
            get {
                return ResourceManager.GetString("alert_reviewname_value_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được.
        /// </summary>
        internal static string alert_rw_value_1 {
            get {
                return ResourceManager.GetString("alert_rw_value_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hài lòng.
        /// </summary>
        internal static string alert_rw_value_2 {
            get {
                return ResourceManager.GetString("alert_rw_value_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm được.
        /// </summary>
        internal static string alert_rw_value_3 {
            get {
                return ResourceManager.GetString("alert_rw_value_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hài lòng.
        /// </summary>
        internal static string alert_rw_value_4 {
            get {
                return ResourceManager.GetString("alert_rw_value_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất hài lòng.
        /// </summary>
        internal static string alert_rw_value_5 {
            get {
                return ResourceManager.GetString("alert_rw_value_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn loại thẻ.
        /// </summary>
        internal static string alert_select_card_type {
            get {
                return ResourceManager.GetString("alert_select_card_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Quận / huyện.
        /// </summary>
        internal static string alert_select_district {
            get {
                return ResourceManager.GetString("alert_select_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hình thức thanh toán.
        /// </summary>
        internal static string alert_select_payment_type {
            get {
                return ResourceManager.GetString("alert_select_payment_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Tỉnh / Thành phố.
        /// </summary>
        internal static string alert_select_provice {
            get {
                return ResourceManager.GetString("alert_select_provice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đơn hàng: .
        /// </summary>
        internal static string alert_shipping_free_1 {
            get {
                return ResourceManager.GetString("alert_shipping_free_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí giao hàng.
        /// </summary>
        internal static string alert_shipping_free_2 {
            get {
                return ResourceManager.GetString("alert_shipping_free_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí giao hàng .
        /// </summary>
        internal static string alert_shipping_free_delivery_charges {
            get {
                return ResourceManager.GetString("alert_shipping_free_delivery_charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miễn phí.
        /// </summary>
        internal static string alert_shipping_free_FREE {
            get {
                return ResourceManager.GetString("alert_shipping_free_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí cồng kềnh .
        /// </summary>
        internal static string alert_shipping_free_free_bulky {
            get {
                return ResourceManager.GetString("alert_shipping_free_free_bulky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí vận chuyển .
        /// </summary>
        internal static string alert_shipping_free_transport_fee {
            get {
                return ResourceManager.GetString("alert_shipping_free_transport_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã ủng hộ Galagala.
        /// </summary>
        internal static string alert_thankyouforchampiongala {
            get {
                return ResourceManager.GetString("alert_thankyouforchampiongala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 5 sản phẩm bán chạy.
        /// </summary>
        internal static string alert_top_5_product_buy {
            get {
                return ResourceManager.GetString("alert_top_5_product_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền các hóa đơn đã thanh toán.
        /// </summary>
        internal static string alert_total_order_paid {
            get {
                return ResourceManager.GetString("alert_total_order_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để xem chi tiết.
        /// </summary>
        internal static string alert_toviewinfo {
            get {
                return ResourceManager.GetString("alert_toviewinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa đánh giá.
        /// </summary>
        internal static string alert_value_value_null {
            get {
                return ResourceManager.GetString("alert_value_value_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có.
        /// </summary>
        internal static string alert_you_have {
            get {
                return ResourceManager.GetString("alert_you_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải đăng nhập trước.
        /// </summary>
        internal static string alert_you_must_be_login {
            get {
                return ResourceManager.GetString("alert_you_must_be_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vừa tạo thành công hóa đơn ID.
        /// </summary>
        internal static string alert_youcreatedorderid {
            get {
                return ResourceManager.GetString("alert_youcreatedorderid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả thương hiệu.
        /// </summary>
        internal static string all_brand {
            get {
                return ResourceManager.GetString("all_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả danh mục.
        /// </summary>
        internal static string all_category {
            get {
                return ResourceManager.GetString("all_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin.
        /// </summary>
        internal static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng dần.
        /// </summary>
        internal static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng.
        /// </summary>
        internal static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        internal static string branch {
            get {
                return ResourceManager.GetString("branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương hiệu.
        /// </summary>
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua tất cả.
        /// </summary>
        internal static string buy_all {
            get {
                return ResourceManager.GetString("buy_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán chạy.
        /// </summary>
        internal static string buy_hot {
            get {
                return ResourceManager.GetString("buy_hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm bán chạy.
        /// </summary>
        internal static string buy_product {
            get {
                return ResourceManager.GetString("buy_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua ngay.
        /// </summary>
        internal static string buynow {
            get {
                return ResourceManager.GetString("buynow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đơn hàng.
        /// </summary>
        internal static string cancel_orders {
            get {
                return ResourceManager.GetString("cancel_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo vệ.
        /// </summary>
        internal static string captchacode {
            get {
                return ResourceManager.GetString("captchacode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ thẻ.
        /// </summary>
        internal static string card_name {
            get {
                return ResourceManager.GetString("card_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        internal static string card_number {
            get {
                return ResourceManager.GetString("card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        internal static string cart {
            get {
                return ResourceManager.GetString("cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua theo danh mục.
        /// </summary>
        internal static string category_buy {
            get {
                return ResourceManager.GetString("category_buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm cùng danh mục.
        /// </summary>
        internal static string category_product {
            get {
                return ResourceManager.GetString("category_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi hình ảnh.
        /// </summary>
        internal static string change_image {
            get {
                return ResourceManager.GetString("change_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ biểu diễn số lượng khách hàng viếng thăm theo thời gian.
        /// </summary>
        internal static string chart_view_visit_count {
            get {
                return ResourceManager.GetString("chart_view_visit_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra.
        /// </summary>
        internal static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngân hàng.
        /// </summary>
        internal static string choose_bank {
            get {
                return ResourceManager.GetString("choose_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn hình ảnh.
        /// </summary>
        internal static string choose_image {
            get {
                return ResourceManager.GetString("choose_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        internal static string colour {
            get {
                return ResourceManager.GetString("colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận xét của bạn.... Tối đa 200 ký tự.
        /// </summary>
        internal static string comment_max_200_length {
            get {
                return ResourceManager.GetString("comment_max_200_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ cửa hàng.
        /// </summary>
        internal static string contact_store {
            get {
                return ResourceManager.GetString("contact_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cước.
        /// </summary>
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        internal static string create_order {
            get {
                return ResourceManager.GetString("create_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string date_created {
            get {
                return ResourceManager.GetString("date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa toàn bộ.
        /// </summary>
        internal static string delete_all {
            get {
                return ResourceManager.GetString("delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán khi nhận hàng.
        /// </summary>
        internal static string delivery_after_receive {
            get {
                return ResourceManager.GetString("delivery_after_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string delivery_and_payment {
            get {
                return ResourceManager.GetString("delivery_and_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán tại điểm bán hàng.
        /// </summary>
        internal static string delivery_at_store {
            get {
                return ResourceManager.GetString("delivery_at_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giao hàng.
        /// </summary>
        internal static string delivery_information {
            get {
                return ResourceManager.GetString("delivery_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm dần.
        /// </summary>
        internal static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết nhà cung cấp.
        /// </summary>
        internal static string detailed_supplier {
            get {
                return ResourceManager.GetString("detailed_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/ huyện.
        /// </summary>
        internal static string district {
            get {
                return ResourceManager.GetString("district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc điểm.
        /// </summary>
        internal static string featured {
            get {
                return ResourceManager.GetString("featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ lọc.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        internal static string gift {
            get {
                return ResourceManager.GetString("gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm quà tặng.
        /// </summary>
        internal static string gift_point {
            get {
                return ResourceManager.GetString("gift_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng lưới.
        /// </summary>
        internal static string grid {
            get {
                return ResourceManager.GetString("grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nổi bật.
        /// </summary>
        internal static string high_lights {
            get {
                return ResourceManager.GetString("high_lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giao dịch.
        /// </summary>
        internal static string history_transaction {
            get {
                return ResourceManager.GetString("history_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        internal static string hot_product {
            get {
                return ResourceManager.GetString("hot_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đồng ý với điều khoản của công ty.
        /// </summary>
        internal static string i_agree_to_the_terms_and_privacy {
            get {
                return ResourceManager.GetString("i_agree_to_the_terms_and_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài nhập.
        /// </summary>
        internal static string import_length {
            get {
                return ResourceManager.GetString("import_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin vận chuyển.
        /// </summary>
        internal static string information_delivery {
            get {
                return ResourceManager.GetString("information_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string information_order {
            get {
                return ResourceManager.GetString("information_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bán hàng.
        /// </summary>
        internal static string information_sale {
            get {
                return ResourceManager.GetString("information_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhà cung cấp.
        /// </summary>
        internal static string information_vendor {
            get {
                return ResourceManager.GetString("information_vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm bạn muốn tìm?.
        /// </summary>
        internal static string input_product {
            get {
                return ResourceManager.GetString("input_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Langague {
            get {
                return ResourceManager.GetString("Langague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dạng cột.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        internal static string list_product {
            get {
                return ResourceManager.GetString("list_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string lost_password {
            get {
                return ResourceManager.GetString("lost_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đtdd.
        /// </summary>
        internal static string mobile_phone {
            get {
                return ResourceManager.GetString("mobile_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        internal static string new_product {
            get {
                return ResourceManager.GetString("new_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề cử.
        /// </summary>
        internal static string nominations {
            get {
                return ResourceManager.GetString("nominations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        internal static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        internal static string old_password {
            get {
                return ResourceManager.GetString("old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang bán.
        /// </summary>
        internal static string on_sale {
            get {
                return ResourceManager.GetString("on_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trực tuyến.
        /// </summary>
        internal static string online_pay {
            get {
                return ResourceManager.GetString("online_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đơn hàng.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng &amp; Trả hàng.
        /// </summary>
        internal static string order_and_return {
            get {
                return ResourceManager.GetString("order_and_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hóa đơn.
        /// </summary>
        internal static string order_code {
            get {
                return ResourceManager.GetString("order_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn hàng.
        /// </summary>
        internal static string order_information {
            get {
                return ResourceManager.GetString("order_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc điểm nổi bật.
        /// </summary>
        internal static string outline {
            get {
                return ResourceManager.GetString("outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán &amp; vận chuyển.
        /// </summary>
        internal static string pay_and_shipping {
            get {
                return ResourceManager.GetString("pay_and_shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thất bại.
        /// </summary>
        internal static string payment_failed {
            get {
                return ResourceManager.GetString("payment_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số đt.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khi nhận hàng.
        /// </summary>
        internal static string post_pay {
            get {
                return ResourceManager.GetString("post_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả trước.
        /// </summary>
        internal static string pre_pay {
            get {
                return ResourceManager.GetString("pre_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước.
        /// </summary>
        internal static string prev {
            get {
                return ResourceManager.GetString("prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá: Cao xuống thấp.
        /// </summary>
        internal static string price_high_to_low {
            get {
                return ResourceManager.GetString("price_high_to_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá: Thấp đến cao.
        /// </summary>
        internal static string price_low_to_high {
            get {
                return ResourceManager.GetString("price_low_to_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách bảo mật.
        /// </summary>
        internal static string private_policy {
            get {
                return ResourceManager.GetString("private_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả sản phẩm.
        /// </summary>
        internal static string product_description {
            get {
                return ResourceManager.GetString("product_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sản phẩm.
        /// </summary>
        internal static string product_details {
            get {
                return ResourceManager.GetString("product_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sản phẩm.
        /// </summary>
        internal static string product_information {
            get {
                return ResourceManager.GetString("product_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string product_number {
            get {
                return ResourceManager.GetString("product_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá gốc.
        /// </summary>
        internal static string product_onlinePrice {
            get {
                return ResourceManager.GetString("product_onlinePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá khuyến mãi.
        /// </summary>
        internal static string product_promotePrice {
            get {
                return ResourceManager.GetString("product_promotePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán lẻ.
        /// </summary>
        internal static string product_retail {
            get {
                return ResourceManager.GetString("product_retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ sản phẩm gồm.
        /// </summary>
        internal static string product_sets {
            get {
                return ResourceManager.GetString("product_sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cá nhân.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        internal static string profile_information {
            get {
                return ResourceManager.GetString("profile_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi.
        /// </summary>
        internal static string promotion {
            get {
                return ResourceManager.GetString("promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/ TP.
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn hàng.
        /// </summary>
        internal static string PSC1 {
            get {
                return ResourceManager.GetString("PSC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hàng.
        /// </summary>
        internal static string PSC2 {
            get {
                return ResourceManager.GetString("PSC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ đợi.
        /// </summary>
        internal static string PSC3 {
            get {
                return ResourceManager.GetString("PSC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuẩn bị.
        /// </summary>
        internal static string PSC4 {
            get {
                return ResourceManager.GetString("PSC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi.
        /// </summary>
        internal static string PSC5 {
            get {
                return ResourceManager.GetString("PSC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá &amp; nhận xét.
        /// </summary>
        internal static string rank_and_comment {
            get {
                return ResourceManager.GetString("rank_and_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá &amp; nhận xét người dùng.
        /// </summary>
        internal static string rating_and_view {
            get {
                return ResourceManager.GetString("rating_and_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem trước.
        /// </summary>
        internal static string re_view {
            get {
                return ResourceManager.GetString("re_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người nhận.
        /// </summary>
        internal static string receive_name {
            get {
                return ResourceManager.GetString("receive_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người nhận.
        /// </summary>
        internal static string receiver_information {
            get {
                return ResourceManager.GetString("receiver_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưa thích.
        /// </summary>
        internal static string relevance {
            get {
                return ResourceManager.GetString("relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        internal static string renew_password {
            get {
                return ResourceManager.GetString("renew_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        internal static string repassword {
            get {
                return ResourceManager.GetString("repassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kết quả.
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm hết.
        /// </summary>
        internal static string sale_out {
            get {
                return ResourceManager.GetString("sale_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi email.
        /// </summary>
        internal static string send_email {
            get {
                return ResourceManager.GetString("send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người gửi.
        /// </summary>
        internal static string sender_information {
            get {
                return ResourceManager.GetString("sender_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ.
        /// </summary>
        internal static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí vận chuyển.
        /// </summary>
        internal static string shippingfee {
            get {
                return ResourceManager.GetString("shippingfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string sign_up {
            get {
                return ResourceManager.GetString("sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản?.
        /// </summary>
        internal static string sign_up_not_account {
            get {
                return ResourceManager.GetString("sign_up_not_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đồng ý với các Điều khoản và Bảo mật của Galagala bao gồm Cookie sử dụng..
        /// </summary>
        internal static string signup_agree_form {
            get {
                return ResourceManager.GetString("signup_agree_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Được bán bởi.
        /// </summary>
        internal static string sold_by {
            get {
                return ResourceManager.GetString("sold_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        internal static string sort_by {
            get {
                return ResourceManager.GetString("sort_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        internal static string special_views {
            get {
                return ResourceManager.GetString("special_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        internal static string specification {
            get {
                return ResourceManager.GetString("specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số kĩ thuật.
        /// </summary>
        internal static string specifications {
            get {
                return ResourceManager.GetString("specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hàng.
        /// </summary>
        internal static string stop_sale {
            get {
                return ResourceManager.GetString("stop_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng nổi bật.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng.
        /// </summary>
        internal static string store_id {
            get {
                return ResourceManager.GetString("store_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cửa hàng.
        /// </summary>
        internal static string store_info {
            get {
                return ResourceManager.GetString("store_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string subtotalfee {
            get {
                return ResourceManager.GetString("subtotalfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string successful {
            get {
                return ResourceManager.GetString("successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thành công.
        /// </summary>
        internal static string successful_payment {
            get {
                return ResourceManager.GetString("successful_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gợi ý sản phẩm.
        /// </summary>
        internal static string suggestions_product {
            get {
                return ResourceManager.GetString("suggestions_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế.
        /// </summary>
        internal static string taxfee {
            get {
                return ResourceManager.GetString("taxfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string term_service {
            get {
                return ResourceManager.GetString("term_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản của công ty.
        /// </summary>
        internal static string terms_of_company {
            get {
                return ResourceManager.GetString("terms_of_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản sử dụng.
        /// </summary>
        internal static string terms_of_usage {
            get {
                return ResourceManager.GetString("terms_of_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương hiệu hàng đầu.
        /// </summary>
        internal static string top_brand {
            get {
                return ResourceManager.GetString("top_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm nổi bật.
        /// </summary>
        internal static string top_product {
            get {
                return ResourceManager.GetString("top_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng GT đơn hàng.
        /// </summary>
        internal static string total_price {
            get {
                return ResourceManager.GetString("total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng sản phẩm.
        /// </summary>
        internal static string total_product {
            get {
                return ResourceManager.GetString("total_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin giao dịch.
        /// </summary>
        internal static string transaction_information {
            get {
                return ResourceManager.GetString("transaction_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí giao dịch.
        /// </summary>
        internal static string transactionfee {
            get {
                return ResourceManager.GetString("transactionfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thanh toán.
        /// </summary>
        internal static string unpaid {
            get {
                return ResourceManager.GetString("unpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string view_all {
            get {
                return ResourceManager.GetString("view_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút gọn.
        /// </summary>
        internal static string view_less {
            get {
                return ResourceManager.GetString("view_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        internal static string view_more {
            get {
                return ResourceManager.GetString("view_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm vừa xem.
        /// </summary>
        internal static string viewed_product {
            get {
                return ResourceManager.GetString("viewed_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bảo hành.
        /// </summary>
        internal static string warranty_information {
            get {
                return ResourceManager.GetString("warranty_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xem.
        /// </summary>
        internal static string watching {
            get {
                return ResourceManager.GetString("watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu thích.
        /// </summary>
        internal static string wishlist {
            get {
                return ResourceManager.GetString("wishlist", resourceCulture);
            }
        }
    }
}
