//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ops
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long LogId { get; set; }
        public string LogName { get; set; }
        public string Description { get; set; }
        public string OrderCode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
