//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ops
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPaid
    {
        public long OrderPaidId { get; set; }
        public long PaymentTypeId { get; set; }
        public string OrderCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerLocation { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<long> CardTypeId { get; set; }
        public Nullable<long> BankId { get; set; }
        public Nullable<long> CardNumber { get; set; }
        public string CardHolderName { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ShipToAddress { get; set; }
        public long ShipToDistrict { get; set; }
        public Nullable<decimal> PriceWeight { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public long ShipToCity { get; set; }
        public string TransactionCode { get; set; }
        public decimal CustomerTotalPaid { get; set; }
        public decimal TransactionFee { get; set; }
        public decimal TotalActualReceive { get; set; }
        public string OrderReceiveDescription { get; set; }
        public string TransactionId { get; set; }
        public string Checksum { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string PaymentTypeBKCode { get; set; }
        public Nullable<int> MerchantSiteId { get; set; }
        public string ListField { get; set; }
        public string ReasonFail { get; set; }
        public string OrderList { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> DateTransaction { get; set; }
        public Nullable<System.DateTime> DateDeliveryEnd { get; set; }
        public Nullable<System.DateTime> DateDeliveryStart { get; set; }
        public Nullable<System.DateTime> DateReceive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> SizeId { get; set; }
        public Nullable<long> SizeGlobalId { get; set; }
        public string Colour { get; set; }
    }
}
