//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.cis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerCard = new HashSet<CustomerCard>();
            this.Wishlist = new HashSet<Wishlist>();
        }
    
        public long CustomerId { get; set; }
        public Nullable<long> CustomerRoleId { get; set; }
        public Nullable<long> SecureAuthenticationId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Career { get; set; }
        public string Address { get; set; }
        public Nullable<long> GiftPoint { get; set; }
        public Nullable<decimal> Xoney { get; set; }
        public string LastIpAddress { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateModifiedPassword { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public Nullable<bool> InBlackList { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string AvatarPhotoUrl { get; set; }
        public string SecurityToken { get; set; }
    
        public virtual ICollection<CustomerCard> CustomerCard { get; set; }
        public virtual ICollection<Wishlist> Wishlist { get; set; }
    }
}
