//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaType
    {
        public MediaType()
        {
            this.Media = new HashSet<Media>();
        }
    
        public long MediaTypeId { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<int> FrameNumb { get; set; }
        public string MediaTypeName { get; set; }
        public string MediaTypeCode { get; set; }
        public string FolderPath { get; set; }
        public Nullable<int> RWidth { get; set; }
        public Nullable<int> RHeight { get; set; }
        public Nullable<long> MinSize { get; set; }
        public Nullable<long> MaxSize { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<Media> Media { get; set; }
    }
}
