//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeGlobal
    {
        public SizeGlobal()
        {
            this.Size = new HashSet<Size>();
        }
    
        public long SizeGlobalId { get; set; }
        public string SizeGlobalName { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<Size> Size { get; set; }
    }
}
