//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Product = new HashSet<Product>();
            this.StoreInMedia = new HashSet<StoreInMedia>();
        }
    
        public long StoreId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string StoreComplexName { get; set; }
        public string Description { get; set; }
        public string Alias { get; set; }
        public string Keywords { get; set; }
        public Nullable<long> VisitCount { get; set; }
        public Nullable<System.DateTime> OnlineDate { get; set; }
        public Nullable<System.DateTime> OfflineDate { get; set; }
        public Nullable<bool> ShowInMallPage { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> ShowInBannerMall { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<StoreInMedia> StoreInMedia { get; set; }
    }
}
