//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.lps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LPS_DBEntities : DbContext
    {
        public LPS_DBEntities()
            : base("name=LPS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProductInventory> ProductInventory { get; set; }
        public DbSet<ProductItem> ProductItem { get; set; }
        public DbSet<ProductItemInSize> ProductItemInSize { get; set; }
    }
}
