//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.lps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItemInSize
    {
        public long ProductItemInSizeId { get; set; }
        public Nullable<long> ProductItemId { get; set; }
        public Nullable<long> SizeId { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
