//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.tts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRecord
    {
        public long SubRecordId { get; set; }
        public long MainRecordId { get; set; }
        public string ContentField { get; set; }
        public string SubList { get; set; }
        public Nullable<int> PreviousSubId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MainRecord MainRecord { get; set; }
    }
}
