//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.GroupAccounts = new HashSet<GroupAccount>();
        }
    
        public long AccountId { get; set; }
        public Nullable<long> OrgRoleId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> DepartmentGroupId { get; set; }
        public long AuthenticationKeyId { get; set; }
        public string StaffId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DepartmentGroup DepartmentGroup { get; set; }
        public virtual ICollection<GroupAccount> GroupAccounts { get; set; }
        public virtual OrgRole OrgRole { get; set; }
    }
}
