//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ams
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMS_DBEntities : DbContext
    {
        public AMS_DBEntities()
            : base("name=AMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<ActionType> ActionTypes { get; set; }
        public DbSet<ActionTypePermission> ActionTypePermissions { get; set; }
        public DbSet<AuthenticationKey> AuthenticationKeys { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<DepartmentGroup> DepartmentGroups { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<ModuleType> ModuleTypes { get; set; }
        public DbSet<OrgRole> OrgRoles { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<SecurityRole> SecurityRoles { get; set; }
        public DbSet<SystemType> SystemTypes { get; set; }
        public DbSet<SystemTypePermission> SystemTypePermissions { get; set; }
        public DbSet<Ward> Wards { get; set; }
        public DbSet<Ship> Ship { get; set; }
        public DbSet<Weight> Weight { get; set; }
    }
}
