//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ams
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationKey
    {
        public long AuthenticationKeyId { get; set; }
        public string HashToken { get; set; }
        public string SaltToken { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
