//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ams
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemTypePermission
    {
        public long SystemTypePermissionId { get; set; }
        public long SystemTypeId { get; set; }
        public long SecurityRoleId { get; set; }
        public long AccountId { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateActive { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SystemType SystemType { get; set; }
    }
}
