//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.tts
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainRecord
    {
        public MainRecord()
        {
            this.SubRecords = new HashSet<SubRecord>();
        }
    
        public long MainRecordId { get; set; }
        public Nullable<long> PriorityId { get; set; }
        public string StatusProcessCode { get; set; }
        public string StatusDirectionCode { get; set; }
        public long TaskDirectionId { get; set; }
        public long OriginatorId { get; set; }
        public string TaskFormCode { get; set; }
        public string FormId { get; set; }
        public string DocumentId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<long> HoldByManagerId { get; set; }
        public Nullable<long> HoldByStaffId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<SubRecord> SubRecords { get; set; }
    }
}
