//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.sms
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLog_mss
    {
        public long ProductLog_mssId { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Content { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
