//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long ArticleId { get; set; }
        public Nullable<long> ArticleTypeId { get; set; }
        public string Title { get; set; }
        public string Introduction { get; set; }
        public string ArticleContent { get; set; }
        public Nullable<long> Code { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<int> Version { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DatePublish { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
    }
}
