//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.ProductInMedia = new HashSet<ProductInMedia>();
            this.StoreInMedia = new HashSet<StoreInMedia>();
        }
    
        public long MediaId { get; set; }
        public Nullable<long> MediaTypeId { get; set; }
        public string MediaName { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MediaType MediaType { get; set; }
        public virtual ICollection<ProductInMedia> ProductInMedia { get; set; }
        public virtual ICollection<StoreInMedia> StoreInMedia { get; set; }
    }
}
