//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInMedia
    {
        public long StoreInMediaId { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> MediaId { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Store Store { get; set; }
    }
}
