//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.ams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public long WeightId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> WeightFrom { get; set; }
        public Nullable<int> WeightTo { get; set; }
        public string DateLimited { get; set; }
        public string Type { get; set; }
        public Nullable<long> TargetId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
