//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ProductInCategory = new HashSet<ProductInCategory>();
        }
    
        public long CategoryId { get; set; }
        public Nullable<long> LogoMediaId { get; set; }
        public Nullable<long> BannerMediaId { get; set; }
        public Nullable<long> ParentCateId { get; set; }
        public Nullable<int> CateLevel { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string CategoryName { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public Nullable<long> VisitCount { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<ProductInCategory> ProductInCategory { get; set; }
    }
}
