//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.mss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        public long GiftId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> BannerMediaId { get; set; }
        public string GiftName { get; set; }
        public string Description { get; set; }
        public Nullable<double> GiftPrice { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
