//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.sts
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageStatistic
    {
        public long HomePageStatisticId { get; set; }
        public Nullable<long> HomePageId { get; set; }
        public Nullable<long> Counter { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Content { get; set; }
    }
}
