//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTelecom.Domain.Core.DataContext.acs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public long AdsId { get; set; }
        public Nullable<long> AdsContentId { get; set; }
        public Nullable<long> AdsTypeId { get; set; }
        public Nullable<long> ContractId { get; set; }
        public Nullable<long> AdsCustomerId { get; set; }
        public Nullable<long> CounterCardId { get; set; }
        public string ReservationCode { get; set; }
        public Nullable<long> Views { get; set; }
        public Nullable<long> ClickThroughs { get; set; }
        public Nullable<System.DateTime> OnlineDate { get; set; }
        public Nullable<System.DateTime> OfflineDate { get; set; }
        public Nullable<long> PeriodOnline { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual AdsContent AdsContent { get; set; }
    }
}
